### ISSUE TITLE
Mobian

### ISSUE THREAD

**Issue by junocomp** [egormanga/spi-i2c-tiny6212#1]
Hi, I installed the DKMS driver from your git.

How do I enable the fingerprint reader on Phosh? I have fprintd installed as well.

**Comment by egormanga** [comment]
This is a driver for the SPI bridge included in the sensor case, not the sensor itself. Nor does it have any functionality related to fingerprints. You need it to communicate with the module (that part is finished), but the module itself has no use for now.

The development of a [libfprint driver](https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/459) has stalled since I moved to a new Android phone and thus mostly lost the motivation. If enough people will ask, I'll consider continuing the development.

Closing as not related; please move to a relevant place (libfprint issue or the driver repo).
